import { NextResponse } from "next/server";
import { createClient as createSupabaseClient } from "@supabase/supabase-js";
import { createClient } from "@/utils/supabase/server";

export async function POST(request: Request) {
  const supabaseUser = await createClient();
  
  const supabaseAdmin = createSupabaseClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    }
  );

  // Authenticate caller
  const { data: { user } } = await supabaseUser.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized - Please sign in to create shop accounts." }, { status: 401 });
  }

  let callerRole = user.app_metadata?.role || user.user_metadata?.role;
  if (!callerRole) {
    const { data: profile } = await supabaseAdmin
      .from("profiles")
      .select("role")
      .eq("id", user.id)
      .maybeSingle();
    callerRole = profile?.role;
  }

  if (callerRole !== "super_admin" && callerRole !== "admin") {
    return NextResponse.json({ error: "Forbidden - Admin access required" }, { status: 403 });
  }

  try {
    const body = await request.json();
    const { 
      organization_id, 
      name, 
      owner_name, 
      address, 
      phone, 
      state_id, 
      district_id, 
      city, 
      language_id, 
      logo_url,
      owner_email,
      owner_password,
      plan_name,
      start_date,
      end_date,
      selected_rates,
      association_id,
      owner_phone
    } = body;

    // Validation
    if (!name || !owner_name || !owner_email || !owner_password) {
      return NextResponse.json({ error: "Missing required fields: Store Name, Owner Name, Login Email, and Password." }, { status: 400 });
    }

    if (owner_password.length < 6) {
      return NextResponse.json({ error: "Password must be at least 6 characters long." }, { status: 400 });
    }

    let cleanEmail = owner_email.replace(/\s+/g, "").toLowerCase();
    if (!cleanEmail.includes("@")) {
      // Strip any characters that aren't digits or a leading +
      const cleanPhone = cleanEmail.replace(/[^0-9+]/g, "");
      cleanEmail = `${cleanPhone}@aurumflow.com`;
    }

    // Auto-generate Unique Shop Code (e.g. SHOP-58291)
    const randomSuffix = Math.floor(10000 + Math.random() * 90000);
    const autoGeneratedShopCode = `SHOP-${randomSuffix}`;

    // 1. Resolve Organization ID
    let validOrgId = organization_id;
    if (!validOrgId) {
      const { data: existingOrg } = await supabaseAdmin.from("organizations").select("id").limit(1).maybeSingle();
      if (existingOrg) {
        validOrgId = existingOrg.id;
      } else {
        const { data: newOrg } = await supabaseAdmin.from("organizations").insert([{ name: "Default Retailers Group" }]).select("id").single();
        validOrgId = newOrg?.id;
      }
    }

    // 2. Resolve State details
    let validStateId = state_id;
    let stateName = "Tamil Nadu";
    if (validStateId) {
      const { data: st } = await supabaseAdmin.from("states").select("id, name").eq("id", validStateId).maybeSingle();
      if (st) stateName = st.name;
    } else {
      const { data: st } = await supabaseAdmin.from("states").select("id, name").limit(1).maybeSingle();
      if (st) {
        validStateId = st.id;
        stateName = st.name;
      }
    }

    // 3. Resolve District details
    let validDistrictId = district_id;
    let districtName = "Chennai";
    if (validDistrictId) {
      const { data: dt } = await supabaseAdmin.from("districts").select("id, name").eq("id", validDistrictId).maybeSingle();
      if (dt) districtName = dt.name;
    } else if (validStateId) {
      const { data: dt } = await supabaseAdmin.from("districts").select("id, name").eq("state_id", validStateId).limit(1).maybeSingle();
      if (dt) {
        validDistrictId = dt.id;
        districtName = dt.name;
      }
    }

    // 4. Resolve Language details
    let validLangId = language_id;
    let langName = "English";
    if (validLangId) {
      const { data: lg } = await supabaseAdmin.from("languages").select("id, language_name").eq("id", validLangId).maybeSingle();
      if (lg) langName = lg.language_name;
    } else {
      const { data: lg } = await supabaseAdmin.from("languages").select("id, language_name").limit(1).maybeSingle();
      if (lg) {
        validLangId = lg.id;
        langName = lg.language_name;
      }
    }

    const shopInitialStatus = callerRole === "super_admin" ? "active" : "pending";
    const subInitialStatus = callerRole === "super_admin" ? "active" : "pending_approval";

    // 5. Create or find Auth User for Shop Owner
    let authUserId: string | null = null;

    const { data: authUser, error: authErr } = await supabaseAdmin.auth.admin.createUser({
      email: cleanEmail,
      password: owner_password,
      email_confirm: true,
      user_metadata: { role: "shop_user", name: owner_name },
      app_metadata: { role: "shop_user" }
    });

    if (authUser?.user) {
      authUserId = authUser.user.id;
    } else if (authErr) {
      // Find existing user if email is registered
      const { data: searchUsers } = await supabaseAdmin.auth.admin.listUsers({ page: 1, perPage: 1000 });
      const existing = searchUsers?.users?.find(u => u.email?.toLowerCase() === cleanEmail);
      if (existing) {
        authUserId = existing.id;
        await supabaseAdmin.auth.admin.updateUserById(existing.id, {
          password: owner_password,
          user_metadata: { role: "shop_user", name: owner_name },
          app_metadata: { role: "shop_user" }
        });
      } else {
        console.error("Auth User Creation Error:", authErr);
        return NextResponse.json({ error: authErr.message || "Failed to create shop owner login account." }, { status: 400 });
      }
    }

    if (!authUserId) {
      return NextResponse.json({ error: "Failed to resolve shop owner account credentials." }, { status: 400 });
    }

    // Dates calculation
    const today = new Date();
    const defaultEnd = new Date(today);
    defaultEnd.setFullYear(defaultEnd.getFullYear() + 1);

    const subStartDate = start_date || today.toISOString().split("T")[0];
    const subEndDate = end_date || defaultEnd.toISOString().split("T")[0];

    // 6. Insert Shop record
    const { data: shop, error: shopErr } = await supabaseAdmin
      .from("shops")
      .insert([{
        shop_code: autoGeneratedShopCode,
        organization_id: validOrgId,
        name,
        owner_name,
        address: address || "Store Address",
        phone: phone || "0000000000",
        owner_phone: owner_phone || null,
        state: stateName,
        state_id: validStateId,
        district: districtName,
        district_id: validDistrictId,
        city: city || "City",
        language: langName,
        language_id: validLangId,
        logo_url: logo_url || "",
        status: shopInitialStatus,
        assigned_sales_admin_id: user.id,
        created_by: user.id,
        selected_rates: selected_rates || ['rate_22k_1g', 'rate_22k_8g', 'rate_silver_1g'],
        association_id: association_id || null
      }])
      .select()
      .single();

    if (shopErr) {
      console.error("Shop insert error:", shopErr);
      return NextResponse.json({ error: shopErr.message }, { status: 400 });
    }

    // 7. Link profile to newly created shop
    const { error: linkErr } = await supabaseAdmin
      .from("profiles")
      .update({ 
        shop_id: shop.id, 
        name: owner_name, 
        managed_by: user.id 
      })
      .eq("id", authUserId);

    if (linkErr) {
      console.error("Link profile to shop error:", linkErr);
    }

    // 8. Create subscription record
    await supabaseAdmin
      .from("subscriptions")
      .insert([{
        shop_id: shop.id,
        status: subInitialStatus,
        plan: plan_name || "Standard",
        start_date: subStartDate,
        end_date: subEndDate,
        created_by: user.id,
        approved_by: callerRole === "super_admin" ? user.id : null
      }]);

    return NextResponse.json({ 
      success: true, 
      shopId: shop.id, 
      shopCode: autoGeneratedShopCode,
      status: shopInitialStatus,
      onboardedBy: user.email
    });
  } catch (err: any) {
    console.error("Onboarding endpoint catch error:", err);
    return NextResponse.json({ error: err.message || "Onboarding failed" }, { status: 500 });
  }
}
